export class ProdutoCatalogoResponse{
    id:string;
    codigo:string;
    codigoFabricante:string;
    fabricante:string;
    codAlfanumericoFabricante:string;
    descricaoCompleta:string;
    idCapacidade:string;
    capacidade:string;
    idCiclo:string;
    ciclo:string;
    idTipoUnidade:string;
    tipoUnidade:string;
    idDescargaCondensadora:string;
    descargaCondensadora:string;
    idVoltagem:string;
    voltagem:string;
    imagem:boolean;
    ativo:boolean;
}