export class DadosOrcamento {
    Loja: string;
    Orcamento: number | string;
    Status: string;
    PrePedido: string;
    Pedido: string;
    Vendedor: string;
    Indicador: string;
    IndicadorVendedor: string;
    IdCliente: string;
    UsuarioCadastro: string;
    UF: string;
    TipoCliente: string;
    ContribuinteIcms: string;
    QtdeMsgPendente: number;
    EntregaImediata: string;
    PrevisaoEntrega: Date;
    InstaladorInstala: string;
    ComissaoOpcao1: number;
    DescMedioAVistaOpcao1:number;
    DescMedioAPrazoOpcao1:number;
    FormaPagtoAVistaOpcao1: string;
    ValorFormaPagtoAVistaOpcao1: number;
    StatusDescSuperiorAVistaOpcao1: string;
    FormaPagtoAPrazoOpcao1:string;
    ValorFormaPagtoAPrazoOpcao1:number;
    QtdeParcelasFormaPagtoAPrazoOpcao1:number;
    StatusDescSuperiorAPrazoOpcao1:string;
    ComissaoOpcao2: number;
    DescMedioAVistaOpcao2:number;
    DescMedioAPrazoOpcao2:number;
    FormaPagtoAVistaOpcao2: string;
    ValorFormaPagtoAVistaOpcao2: number;
    StatusDescSuperiorAVistaOpcao2: string;
    FormaPagtoAPrazoOpcao2:string;
    ValorFormaPagtoAPrazoOpcao2:number;
    QtdeParcelasFormaPagtoAPrazoOpcao2:number;
    StatusDescSuperiorAPrazoOpcao2:string;
    ComissaoOpcao3: number;
    DescMedioAVistaOpcao3:number;
    DescMedioAPrazoOpcao3:number;
    FormaPagtoAVistaOpcao3: string;
    ValorFormaPagtoAVistaOpcao3: number;
    StatusDescSuperiorAVistaOpcao3: string;
    FormaPagtoAPrazoOpcao3:string;
    ValorFormaPagtoAPrazoOpcao3:number;
    QtdeParcelasFormaPagtoAPrazoOpcao3:number;
    StatusDescSuperiorAPrazoOpcao3:string;
    OpcaoAprovada: number;
    ComissaoOpcaoAprovada:number;
    DescMedioOpcaoAprovada:number;
    FormaPagtoOpcaoAprovada: string;
    ValorFormaPagtoOpcaoAprovada: number;
    QtdeParcelasFormaOpcaoAprovada: number;
    StatusDescSuperiorOpcaoAprovada: string;
    DataCadastro: Date;
    Validade: Date
}